### ISSUE TITLE
jshint does not like `new xError`

### ISSUE THREAD

**Issue by colthreepv** [yzarubin/x-error#4]
As it's written here: http://jslinterrors.com/a-constructor-name-should-start-with-an-uppercase-letter

would be nice if the the module would respect javascript conventions

**Comment by yzarubin** [comment]
Good point. I've been thinking more about the constructor, I'll come back to this in a few days after I formulate my thoughts.

**Comment by yzarubin** [comment]
As for the module name, I suppose it would be either Xerror or XError, I personally prefer the latter. Also, what do you think of  the following changes:

1) Remove "code" from the constructor, it doesn't seem useful. You'd still be able to call setCode()
2) More closely mimic vanilla Error's message constructor, where it sets the message property by calling toString() on whatever is passed in, with the exception of objects. If an object is passed into the constructor, keep the current behaviour of calling extend(arg).
3) What do you think of changing setHttpCode and setHttpResponse to something more generic like setStatus and setResponse respectively?
4) Change setMsg to setMessage for consistency.
5) What do you think of changing API from calling new xError() to just xError(), which would return a new instance. Would avoid having to call new every time which tends to be fashionable these days, but it might be not intuitive since most devs are used to calling new Error(). I'm torn in this area.

If you have any other API suggestions I'm all ears.

**Comment by colthreepv** [comment]
> 1) Remove "code" from the constructor, it doesn't seem useful. You'd still be able to call setCode()

I agree that it's a bit confusing (my PR is wrong about that).
It might lead other people to misuse it  between  `setCode()` and `setHttpCode()`.
Regarding remove: I'm a bit against, it does not hurt as the constructor accepts string/object/number, and when people learn to enumerate their errors can help in debugging (and also in documentation)

> 2) More closely mimic vanilla Error's message constructor, where it sets the message property by calling toString() on whatever is passed in, with the exception of objects. If an object is passed into the constructor, keep the current behaviour of calling extend(arg).

quite good!

> 3) What do you think of changing setHttpCode and setHttpResponse to something more generic like setStatus and setResponse respectively?

I have not a clear idea on this, I don't see many others use cases for responses/statuses beside http.
Although having a more generic name seems a plus, nothing bad can come from it :+1: 

> 4) Change setMsg to setMessage for consistency.

Sure, there are short names anyway.

> 5) What do you think of changing API from calling new xError() to just xError(), which would return a new instance. Would avoid having to call new every time which tends to be fashionable these days, but it might be not intuitive since most devs are used to calling new Error(). I'm torn in this area.

Mh hard choice.
I would keep it this way to keep it in line with vanilla `Error`
I've googled extensively and found [another lib from hapijs](https://github.com/hapijs/boom) that does not use `new`, but is not any shorter since it uses `.create()`
I think it's possible to support both: `new xError()` and just `xError()` just type checking.
It's actually a choice if you want to spoil users or just let them use `xError` as a wrapper to `Error`, I would go for the latter

last note: I went for `XError` in my code :)
