### ISSUE TITLE
[discussion] Ship with a default errorhandler

### ISSUE THREAD

**Issue by colthreepv** [yzarubin/x-error#5]
Hello, as I see quite many projects depends on [expressjs/errorhandler](https://www.npmjs.com/package/errorhandler), It might be a good idea customize this project to use XError
It _might_ overblown this package, but I think most common use-case is that

Opening this for discussion as it will require some thinkering

**Comment by yzarubin** [comment]
Interesting. I don't have any experience with that package as I've never encountered it on the projects I was involved with, but it looks like it's intended purpose is development use only. Is that what you have in mind as well? The error handlers implementing X-Error that I've done so far were for both production and development purposes.

**Comment by colthreepv** [comment]
Yes, it's kind of a _reference_ error handler, to see how it can be done, and that is why I think a working example with XError might be useful for new users...

big thumbup for new documentation :+1:, If I come up with a generic-enough errorhandler implementation I would PR it

**Comment by yzarubin** [comment]
Thanks, the documentation is still a work in progress, any feedback is welcome.

I guess as for error handlers, I'd be interested to figure out how others do it. Since I made X-Error, I ended up abstracting out the response object entirely. Every controller is a function of only the `req` object and returns a promise, if it is resolved, then server returns a 200 and the result. If it is an error, the abstraction layer uses httpCode and httpResponse of the error to figure out what to do with it. Every controller is then registered inside this abstraction. It ends up being very powerful, though I think its probably too large of an abstraction for most people, so perhaps we'd want something more simple. How did you end up implementing your error handler?

**Comment by colthreepv** [comment]
Interesting, that asks for a gist!
My implementation is simpler, my controllers are not entirely promises, they are simple functions returning status 200 when everything goes fine.

All other asynchronous operations are wrapped in a `Promise(s)`, each `Promise` chain ends with a `.catch(next)`
I wrap any errors from third-party libraries in XError, some of them are expected, so I assign a known code+statusCode+message, others are not expected (like `connection lost` to db or some REST service) and return a generic error 500, adding error data with `.debug(err)`

Then in the errorhandler I dump debug data to a file for later inspection, differentiate between coding errors (they are simple `Error` instances instead of `XError`), "handled errors" (statusCode < 500) and generics (500)

You provided me with some food for thought, thanks

**Comment by yzarubin** [comment]
[This is what I'm doing in essence.](https://gist.github.com/yzarubin/20df0cc92810b2ad67d4) Be wary of mistakes as I just wrote that.

I think what you're doing is pretty much ideal as an example, as it would work with the majority of current express implementations. It also works with both promises and callbacks!
